apiVersion: apps/v1
kind: Deployment
metadata:
  name: xxl-job-admin
  namespace: youlai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xxl-job-admin
  template:
    metadata:
      labels:
        app: xxl-job-admin
    spec:
      containers:
        - name: xxl-job-admin
          image: xuxueli/xxl-job-admin:3.2.0
          env:
            - name: XXL_JOB_ADMIN_PORT
              value: "8080"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://my-mysql-primary.mysql.svc.cluster.local/xxl_job?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: "123456"
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: xxl-job-admin
  namespace: youlai
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.56.241   # 指定固定 IP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: xxl-job-admin
