apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-nacos
  namespace: monitoring             # Prometheus 所在命名空间
  labels:
    release: prometheus            # Prometheus release 标签
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nacos
  namespaceSelector:
    matchNames:
      - youlai                     # Nacos Service 所在命名空间
  endpoints:
    - port: "server"               # 对应 Nacos Service 的端口名称
      path: /nacos/actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
